[build]
base = ""
publish = "target"

[build.environment]
JAVA_HOME = "/opt/buildhome/.jdk"

[[plugins]]
package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    commands = [
      './mvnw clean package -DskipTests'
    ]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
