[build]
command = "chmod +x mvnw && ./mvnw clean package -DskipTests"
base = ""
publish = "target"

[build.environment]
JAVA_HOME = "/opt/buildhome/.jdk"
JAVA_OPTS = "-Xmx512m -Xms256m"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
